[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
description = "Mobile project generator for hilen"
edition = "2024"
homepage = "https://github.com/hilen/hilen-mobile"
license = "MIT OR Apache-2.0"
name = "hilen-mobile"
repository = "https://github.com/hilen/hilen-mobile"
version = "0.6.2"

[[bin]]
name = "hilen-mobile"

[dependencies]
anyhow = { workspace = true }
convert_case = { workspace = true }
structopt = { workspace = true }
toml = { workspace = true }
