[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "hilen-mobile-game"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "hilen_mobile_game"

[dependencies]
hilen = { git = "https://github.com/hilen/hilen.git", rev = "cf11e44d" }
#hilen = { path = "../../hilen/hilen" }
