name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
          { runner: tc }
        ]
    runs-on: [self-hosted, "${{ matrix.target.runner }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          submodules: recursive

      - name: Add the NixOS tool folders to PATH
        run: echo "/run/current-system/sw/bin" >> "$GITHUB_PATH"

      - name: Build
        run: cargo build
